# Generated by Django 5.2 on 2025-04-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_competition_project_details_project_market_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('compensation_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('equity', 'Equity Split')], default='unpaid', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.project')),
            ],
        ),
    ]
