# Generated by Django 4.2.7 on 2025-07-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Application'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('message', 'Message'), ('direct_message', 'Direct Message')], max_length=20),
        ),
    ]
