# Generated by Django 5.2 on 2025-09-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_investment_userprojectanalytics_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalystReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0, help_text='Overall risk score (0-100, lower is better)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20)),
                ('tam_inflation_risk', models.FloatField(default=0.0, help_text='TAM inflation risk (0-100)')),
                ('financial_consistency_risk', models.FloatField(default=0.0, help_text='Financial consistency risk (0-100)')),
                ('market_saturation_risk', models.FloatField(default=0.0, help_text='Market saturation risk (0-100)')),
                ('competition_risk', models.FloatField(default=0.0, help_text='Competition risk (0-100)')),
                ('team_risk', models.FloatField(default=0.0, help_text='Team risk (0-100)')),
                ('growth_score', models.FloatField(default=0.0, help_text='Growth potential score (0-100)')),
                ('growth_index', models.CharField(choices=[('low', 'Low Growth'), ('medium', 'Medium Growth'), ('high', 'High Growth'), ('exceptional', 'Exceptional Growth')], default='medium', max_length=20)),
                ('traction_score', models.FloatField(default=0.0, help_text='Traction score (0-100)')),
                ('hiring_momentum', models.FloatField(default=0.0, help_text='Hiring momentum (0-100)')),
                ('market_demand_score', models.FloatField(default=0.0, help_text='Market demand score (0-100)')),
                ('scalability_potential', models.FloatField(default=0.0, help_text='Scalability potential (0-100)')),
                ('sector_rank', models.IntegerField(default=0, help_text='Rank within sector (1=best)')),
                ('sector_percentile', models.FloatField(default=0.0, help_text='Percentile within sector (0-100)')),
                ('platform_rank', models.IntegerField(default=0, help_text='Overall platform rank')),
                ('platform_percentile', models.FloatField(default=0.0, help_text='Overall platform percentile (0-100)')),
                ('vs_sector_avg', models.FloatField(default=0.0, help_text='Score vs sector average')),
                ('vs_platform_avg', models.FloatField(default=0.0, help_text='Score vs platform average')),
                ('vs_similar_stage', models.FloatField(default=0.0, help_text='Score vs similar stage startups')),
                ('risk_analysis', models.TextField(blank=True, help_text='Detailed risk analysis')),
                ('growth_analysis', models.TextField(blank=True, help_text='Detailed growth analysis')),
                ('peer_analysis', models.TextField(blank=True, help_text='Detailed peer benchmarking analysis')),
                ('recommendations', models.TextField(blank=True, help_text='AI recommendations for investors')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ai_model_version', models.CharField(default='v1.0', max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='main.project')),
            ],
            options={
                'ordering': ['-growth_score', '-risk_score'],
            },
        ),
    ]
